import { type BusinessTypeOption, type BusinessType, type VerticalConfig } from '@/types';

export const BUSINESS_TYPES: BusinessTypeOption[] = [
  {
    id: 'restaurant',
    name: 'Restaurant',
    description: 'AR menus, food showcases, and table QR experiences',
    icon: 'UtensilsCrossed',
    arExperienceLabel: 'AR Menu',
    productLabel: { singular: 'Dish', plural: 'Dishes' },
    color: '#F97316',
    gradient: 'from-orange-500 to-red-500',
  },
  {
    id: 'retail',
    name: 'Retail Store',
    description: 'Product showcases, promotions, and shelf AR displays',
    icon: 'ShoppingBag',
    arExperienceLabel: 'AR Showcase',
    productLabel: { singular: 'Product', plural: 'Products' },
    color: '#3B82F6',
    gradient: 'from-blue-500 to-cyan-500',
  },
  {
    id: 'furniture',
    name: 'Furniture',
    description: 'Room placement AR, furniture preview, and space visualization',
    icon: 'Armchair',
    arExperienceLabel: 'AR Preview',
    productLabel: { singular: 'Furniture Item', plural: 'Furniture Items' },
    color: '#8B5CF6',
    gradient: 'from-violet-500 to-purple-600',
  },
  {
    id: 'jewelry',
    name: 'Jewelry',
    description: 'Luxury catalogs, wrist/neck try-on simulations',
    icon: 'Gem',
    arExperienceLabel: 'AR Catalog',
    productLabel: { singular: 'Piece', plural: 'Pieces' },
    color: '#EC4899',
    gradient: 'from-pink-500 to-rose-500',
  },
  {
    id: 'real_estate',
    name: 'Real Estate',
    description: 'Property tours, apartment showcases, and floor plan viewers',
    icon: 'Building2',
    arExperienceLabel: 'AR Tour',
    productLabel: { singular: 'Property', plural: 'Properties' },
    color: '#10B981',
    gradient: 'from-emerald-500 to-teal-500',
  },
  {
    id: 'automotive',
    name: 'Automotive',
    description: 'Vehicle viewers, dealership experiences, color configurators',
    icon: 'Car',
    arExperienceLabel: 'AR Showroom',
    productLabel: { singular: 'Vehicle', plural: 'Vehicles' },
    color: '#EF4444',
    gradient: 'from-red-500 to-orange-500',
  },
  {
    id: 'general',
    name: 'General Business',
    description: 'Universal product templates and promotional campaigns',
    icon: 'Briefcase',
    arExperienceLabel: 'AR Experience',
    productLabel: { singular: 'Product', plural: 'Products' },
    color: '#6366F1',
    gradient: 'from-indigo-500 to-blue-500',
  },
];

export const VERTICAL_CONFIGS: Record<BusinessType, VerticalConfig> = {
  restaurant: {
    productLabels: { singular: 'Dish', plural: 'Dishes' },
    arExperienceLabel: 'AR Menu',
    dashboardWidgets: ['totalDishes', 'arLaunches', 'menuScans', 'topDishes'],
    productFormFields: [
      { name: 'name', label: 'Dish Name', type: 'text', required: true, placeholder: 'e.g., Truffle Risotto' },
      { name: 'cuisineType', label: 'Cuisine Type', type: 'select', required: true, options: ['Italian', 'Indian', 'Chinese', 'Japanese', 'Mexican', 'American', 'French', 'Thai', 'Other'] },
      { name: 'price', label: 'Price', type: 'number', required: true, placeholder: '0.00' },
      { name: 'description', label: 'Description', type: 'textarea', required: false, placeholder: 'Describe the dish...' },
      { name: 'isSpecial', label: 'Daily Special', type: 'select', required: false, options: ['Yes', 'No'] },
    ],
    recommendedTemplateCategories: ['ar-menu', 'food-showcase', 'qr-table-menu'],
    analyticsKPILabels: { scans: 'Menu Scans', arLaunches: 'AR Views', duration: 'Avg. View Time' },
    geometryTemplate: 'plate',
  },
  retail: {
    productLabels: { singular: 'Product', plural: 'Products' },
    arExperienceLabel: 'AR Showcase',
    dashboardWidgets: ['totalProducts', 'arLaunches', 'productScans', 'topProducts'],
    productFormFields: [
      { name: 'name', label: 'Product Name', type: 'text', required: true, placeholder: 'e.g., Wireless Headphones' },
      { name: 'sku', label: 'SKU', type: 'text', required: false, placeholder: 'SKU-001' },
      { name: 'category', label: 'Category', type: 'select', required: true, options: ['Electronics', 'Clothing', 'Accessories', 'Home & Garden', 'Sports', 'Beauty', 'Other'] },
      { name: 'price', label: 'Price', type: 'number', required: true, placeholder: '0.00' },
      { name: 'description', label: 'Description', type: 'textarea', required: false, placeholder: 'Describe the product...' },
    ],
    recommendedTemplateCategories: ['product-showcase', 'promotional-campaign', 'shelf-ar'],
    analyticsKPILabels: { scans: 'Product Scans', arLaunches: 'AR Previews', duration: 'Avg. View Time' },
    geometryTemplate: 'box',
  },
  furniture: {
    productLabels: { singular: 'Furniture Item', plural: 'Furniture Items' },
    arExperienceLabel: 'AR Preview',
    dashboardWidgets: ['totalItems', 'arLaunches', 'roomPlacements', 'topItems'],
    productFormFields: [
      { name: 'name', label: 'Item Name', type: 'text', required: true, placeholder: 'e.g., Modern Sofa' },
      { name: 'category', label: 'Category', type: 'select', required: true, options: ['Sofa', 'Chair', 'Table', 'Bed', 'Cabinet', 'Shelf', 'Lamp', 'Other'] },
      { name: 'dimensions', label: 'Dimensions (W×D×H cm)', type: 'text', required: false, placeholder: '200×90×85' },
      { name: 'price', label: 'Price', type: 'number', required: true, placeholder: '0.00' },
      { name: 'description', label: 'Description', type: 'textarea', required: false, placeholder: 'Describe the item...' },
    ],
    recommendedTemplateCategories: ['room-placement', 'furniture-preview', 'space-viz'],
    analyticsKPILabels: { scans: 'Item Scans', arLaunches: 'AR Placements', duration: 'Avg. View Time' },
    geometryTemplate: 'box',
  },
  jewelry: {
    productLabels: { singular: 'Piece', plural: 'Pieces' },
    arExperienceLabel: 'AR Catalog',
    dashboardWidgets: ['totalPieces', 'arLaunches', 'catalogViews', 'topPieces'],
    productFormFields: [
      { name: 'name', label: 'Piece Name', type: 'text', required: true, placeholder: 'e.g., Diamond Solitaire Ring' },
      { name: 'jewelryType', label: 'Jewelry Type', type: 'select', required: true, options: ['Ring', 'Necklace', 'Bracelet', 'Earring', 'Pendant', 'Watch', 'Other'] },
      { name: 'material', label: 'Material', type: 'select', required: false, options: ['Gold', 'Silver', 'Platinum', 'Rose Gold', 'Diamond', 'Other'] },
      { name: 'price', label: 'Price', type: 'number', required: true, placeholder: '0.00' },
      { name: 'description', label: 'Description', type: 'textarea', required: false, placeholder: 'Describe the piece...' },
    ],
    recommendedTemplateCategories: ['product-showcase', 'luxury-catalog', 'try-on'],
    analyticsKPILabels: { scans: 'Catalog Scans', arLaunches: 'AR Try-Ons', duration: 'Avg. View Time' },
    geometryTemplate: 'ring',
  },
  real_estate: {
    productLabels: { singular: 'Property', plural: 'Properties' },
    arExperienceLabel: 'AR Tour',
    dashboardWidgets: ['totalProperties', 'arLaunches', 'tourViews', 'topProperties'],
    productFormFields: [
      { name: 'name', label: 'Property Name', type: 'text', required: true, placeholder: 'e.g., Sunset Villa' },
      { name: 'propertyType', label: 'Property Type', type: 'select', required: true, options: ['Apartment', 'House', 'Villa', 'Condo', 'Townhouse', 'Commercial', 'Land', 'Other'] },
      { name: 'area', label: 'Area (sq ft)', type: 'number', required: false, placeholder: '1500' },
      { name: 'price', label: 'Price', type: 'number', required: true, placeholder: '0' },
      { name: 'description', label: 'Description', type: 'textarea', required: false, placeholder: 'Describe the property...' },
    ],
    recommendedTemplateCategories: ['property-tour', 'apartment-showcase', 'floor-plan'],
    analyticsKPILabels: { scans: 'Property Scans', arLaunches: 'AR Tours', duration: 'Avg. Tour Time' },
    geometryTemplate: 'building',
  },
  automotive: {
    productLabels: { singular: 'Vehicle', plural: 'Vehicles' },
    arExperienceLabel: 'AR Showroom',
    dashboardWidgets: ['totalVehicles', 'arLaunches', 'showroomViews', 'topVehicles'],
    productFormFields: [
      { name: 'name', label: 'Vehicle Name', type: 'text', required: true, placeholder: 'e.g., Tesla Model 3' },
      { name: 'vehicleType', label: 'Vehicle Type', type: 'select', required: true, options: ['Sedan', 'SUV', 'Truck', 'Coupe', 'Hatchback', 'Convertible', 'Van', 'Other'] },
      { name: 'year', label: 'Year', type: 'number', required: false, placeholder: '2024' },
      { name: 'price', label: 'Price', type: 'number', required: true, placeholder: '0' },
      { name: 'description', label: 'Description', type: 'textarea', required: false, placeholder: 'Describe the vehicle...' },
    ],
    recommendedTemplateCategories: ['vehicle-viewer', 'dealership-experience', 'color-configurator'],
    analyticsKPILabels: { scans: 'Vehicle Scans', arLaunches: 'AR Showroom Views', duration: 'Avg. View Time' },
    geometryTemplate: 'box',
  },
  general: {
    productLabels: { singular: 'Product', plural: 'Products' },
    arExperienceLabel: 'AR Experience',
    dashboardWidgets: ['totalProducts', 'arLaunches', 'scans', 'topProducts'],
    productFormFields: [
      { name: 'name', label: 'Product Name', type: 'text', required: true, placeholder: 'Product name' },
      { name: 'category', label: 'Category', type: 'text', required: false, placeholder: 'Category' },
      { name: 'price', label: 'Price', type: 'number', required: false, placeholder: '0.00' },
      { name: 'description', label: 'Description', type: 'textarea', required: false, placeholder: 'Describe the product...' },
    ],
    recommendedTemplateCategories: ['product-showcase', 'promotional-campaign'],
    analyticsKPILabels: { scans: 'Total Scans', arLaunches: 'AR Views', duration: 'Avg. View Time' },
    geometryTemplate: 'plane',
  },
};

export function getBusinessTypeOption(id: BusinessType): BusinessTypeOption {
  return BUSINESS_TYPES.find((bt) => bt.id === id) || BUSINESS_TYPES[BUSINESS_TYPES.length - 1];
}

export function getVerticalConfig(businessType: BusinessType): VerticalConfig {
  return VERTICAL_CONFIGS[businessType] || VERTICAL_CONFIGS.general;
}